name: videomarketing
favicon: null
layout_spectrum: 0.45165022392757237
typography_spectrum: 0.1961555164307356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7400166171137244
  lightness: 0.3530006310902536
  saturation: 0.7363734275568277
  rhythmicContrast: 0.64343555807136
purpose: []
